### ISSUE TITLE
`microsoft365wp_authentication_methods_policy` recreating `authentication_method_configurations`

### ISSUE THREAD

**Issue by mcaulifn** [terraprovider/terraform-provider-microsoft365wp#3]
I am attempting to onboard `microsoft365wp_authentication_methods_policy`. Some of it had been configured already so I imported and successfully linked what was already configured with TF. A plan now shows that `authentication_method_configurations` is going to be recreated, thus increasing the likelihood of a lockout. A DEBUG showed no useful information about why TF is recreating. Any suggestions?

```
# microsoft365wp_authentication_methods_policy.this will be updated in-place
  ~ resource "microsoft365wp_authentication_methods_policy" "this" {
      ~ authentication_method_configurations = [
          - {
              - exclude_targets = [] -> null
              - fido2           = {
                  - include_targets                      = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                  - is_attestation_enforced              = false -> null
                  - is_self_service_registration_allowed = true -> null
                  - key_restrictions                     = {
                      - aa_guids         = [] -> null
                      - enforcement_type = "block" -> null
                      - is_enforced      = false -> null
                    } -> null
                } -> null
              - id              = "Fido2" -> null
              - state           = "enabled" -> null
            },
          - {
              - exclude_targets = [] -> null
              - hardware_oath   = {
                  - include_targets = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                } -> null
              - id              = "HardwareOath" -> null
              - state           = "enabled" -> null
            },
          - {
              - exclude_targets = [] -> null
              - id              = "FederatedIdentityCredential" -> null
              - state           = "disabled" -> null
            },
          - {
              - exclude_targets         = [] -> null
              - id                      = "MicrosoftAuthenticator" -> null
              - microsoft_authenticator = {
                  - feature_settings         = {
                      - companion_app_allowed_state                 = {
                          - exclude_target = {
                              - id          = "00000000-0000-0000-0000-000000000000" -> null
                              - target_type = "group" -> null
                            } -> null
                          - include_target = {
                              - id          = "all_users" -> null
                              - target_type = "group" -> null
                            } -> null
                          - state          = "default" -> null
                        } -> null
                      - display_app_information_required_state      = {
                          - exclude_target = {
                              - id          = "00000000-0000-0000-0000-000000000000" -> null
                              - target_type = "group" -> null
                            } -> null
                          - include_target = {
                              - id          = "all_users" -> null
                              - target_type = "group" -> null
                            } -> null
                          - state          = "default" -> null
                        } -> null
                      - display_location_information_required_state = {
                          - exclude_target = {
                              - id          = "00000000-0000-0000-0000-000000000000" -> null
                              - target_type = "group" -> null
                            } -> null
                          - include_target = {
                              - id          = "all_users" -> null
                              - target_type = "group" -> null
                            } -> null
                          - state          = "default" -> null
                        } -> null
                    } -> null
                  - include_targets          = [
                      - {
                          - authentication_mode      = "any" -> null
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                  - is_software_oath_enabled = true -> null
                } -> null
              - state                   = "enabled" -> null
            },
          - {
              - exclude_targets = [] -> null
              - id              = "Sms" -> null
              - sms             = {
                  - include_targets = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - is_usable_for_sign_in    = true -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                } -> null
              - state           = "enabled" -> null
            },
          - {
              - exclude_targets = [] -> null
              - id              = "SoftwareOath" -> null
              - software_oath   = {
                  - include_targets = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                } -> null
              - state           = "disabled" -> null
            },
          - {
              - exclude_targets       = [] -> null
              - id                    = "TemporaryAccessPass" -> null
              - state                 = "disabled" -> null
              - temporary_access_pass = {
                  - default_length              = 8 -> null
                  - default_lifetime_in_minutes = 60 -> null
                  - include_targets             = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                  - is_usable_once              = false -> null
                  - maximum_lifetime_in_minutes = 480 -> null
                  - minimum_lifetime_in_minutes = 60 -> null
                } -> null
            },
          - {
              - exclude_targets = [] -> null
              - id              = "Voice" -> null
              - state           = "disabled" -> null
              - voice           = {
                  - include_targets         = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                  - is_office_phone_allowed = false -> null
                } -> null
            },
          - {
              - exclude_targets  = [] -> null
              - id               = "X509Certificate" -> null
              - state            = "disabled" -> null
              - x509_certificate = {
                  - authentication_mode_configuration = {
                      - rules                                            = [] -> null
                      - x509_certificate_authentication_default_mode     = "x509CertificateSingleFactor" -> null
                      - x509_certificate_default_required_affinity_level = "low" -> null
                    } -> null
                  - certificate_user_bindings         = [
                      - {
                          - priority               = 1 -> null
                          - trust_affinity_level   = "low" -> null
                          - user_property          = "userPrincipalName" -> null
                          - x509_certificate_field = "PrincipalName" -> null
                        },
                      - {
                          - priority               = 2 -> null
                          - trust_affinity_level   = "low" -> null
                          - user_property          = "userPrincipalName" -> null
                          - x509_certificate_field = "RFC822Name" -> null
                        },
                      - {
                          - priority               = 3 -> null
                          - trust_affinity_level   = "high" -> null
                          - user_property          = "certificateUserIds" -> null
                          - x509_certificate_field = "SubjectKeyIdentifier" -> null
                        },
                    ] -> null
                  - include_targets                   = [
                      - {
                          - id                       = "all_users" -> null
                          - is_registration_required = false -> null
                          - target_type              = "group" -> null
                        },
                    ] -> null
                  - issuer_hints_configuration        = {
                      - state = "disabled" -> null
                    } -> null
                } -> null
            },
          + {
              + exclude_targets = []
              + fido2           = {
                  + include_targets                      = [
                      + {
                          + id                       = "all_users"
                          + is_registration_required = false
                          + target_type              = "group"
                        },
                    ]
                  + is_attestation_enforced              = true
                  + is_self_service_registration_allowed = true
                  + key_restrictions                     = {
                      + aa_guids         = []
                      + enforcement_type = "block"
                      + is_enforced      = false
                    }
                }
              + id              = "Fido2"
              + state           = "enabled"
            },
          + {
              + exclude_targets         = []
              + id                      = "MicrosoftAuthenticator"
              + microsoft_authenticator = {
                  + feature_settings         = {
                      + companion_app_allowed_state                 = {
                          + exclude_target = {
                              + id          = "00000000-0000-0000-0000-000000000000"
                              + target_type = "group"
                            }
                          + include_target = {
                              + id          = "all_users"
                              + target_type = "group"
                            }
                          + state          = "default"
                        }
                      + display_app_information_required_state      = {
                          + exclude_target = {
                              + id          = "00000000-0000-0000-0000-000000000000"
                              + target_type = "group"
                            }
                          + include_target = {
                              + id          = "all_users"
                              + target_type = "group"
                            }
                          + state          = "default"
                        }
                      + display_location_information_required_state = {
                          + exclude_target = {
                              + id          = "00000000-0000-0000-0000-000000000000"
                              + target_type = "group"
                            }
                          + include_target = {
                              + id          = "all_users"
                              + target_type = "group"
                            }
                          + state          = "default"
                        }
                    }
                  + include_targets          = [
                      + {
                          + authentication_mode      = "any"
                          + id                       = "all_users"
                          + is_registration_required = false
                          + target_type              = "group"
                        },
                    ]
                  + is_software_oath_enabled = false
                }
              + state                   = "enabled"
            },
          + {
              + exclude_targets       = []
              + id                    = "TemporaryAccessPass"
              + state                 = "enabled"
              + temporary_access_pass = {
                  + default_length              = 8
                  + default_lifetime_in_minutes = 60
                  + include_targets             = [
                      + {
                          + id                       = "all_users"
                          + is_registration_required = false
                          + target_type              = "group"
                        },
                    ]
                  + is_usable_once              = false
                  + maximum_lifetime_in_minutes = 480
                  + minimum_lifetime_in_minutes = 60
                }
            },
            # (1 unchanged element hidden)
        ]
        id                                   = "authenticationMethodsPolicy"
        # (8 unchanged attributes hidden)
    }
```

**Comment by hcoberdalhoff** [comment]
Hi, can you provide a sample of the code you use to create this?

**Comment by hcoberdalhoff** [comment]
Generally, this can happen when you import resources, as the order of elements in your list might differ from what terraform wants to create.

**Comment by mcaulifn** [comment]
This yaml feeds the resource creation:
(there are some commented sections for testing)

```
---
authentication_method_configurations:
  - email:
      allow_external_id_to_use_email_otp: default
      include_targets: []
    id: Email
    state: enabled
  - fido2:
      include_targets:
        - id: all_users
          is_registration_required: false
          target_type: group
      is_attestation_enforced: true
      is_self_service_registration_allowed: true
      key_restrictions:
        aa_guids: []
        enforcement_type: block
        is_enforced: false
    id: Fido2
    state: enabled
  #- hardware_oath:
  #    include_targets:
  #      - id: all_users
  #        is_registration_required: false
  #        target_type: group
  #id: HardwareOath
  #  state: disabled
  - id: FederatedIdentityCredential
    state: disabled
  - id: MicrosoftAuthenticator
    microsoft_authenticator:
      feature_settings:
        companion_app_allowed_state:
          exclude_target:
            id: 00000000-0000-0000-0000-000000000000
            target_type: group
          include_target:
            id: all_users
            target_type: group
          state: default
        display_app_information_required_state:
          exclude_target:
            id: 00000000-0000-0000-0000-000000000000
            target_type: group
          include_target:
            id: all_users
            target_type: group
          state: default
        display_location_information_required_state:
          exclude_target:
            id: 00000000-0000-0000-0000-000000000000
            target_type: group
          include_target:
            id: all_users
            target_type: group
          state: default
      include_targets:
        - authentication_mode: any
          id: all_users
          is_registration_required: false
          target_type: group
      is_software_oath_enabled: false
    state: enabled
  #- #id: Sms
  #  sms:
  #    include_targets:
  #      - id: all_users
  #        is_registration_required: false
  #        is_usable_for_sign_in: true
  #        target_type: group
  #  state: disabled
  #- id: SoftwareOath
  #  software_oath:
  #    include_targets:
  #      - id: all_users
  #        is_registration_required: false
  #        target_type: group
  #  state: disabled
  - id: TemporaryAccessPass
    state: enabled
    temporary_access_pass:
      default_length: 8
      default_lifetime_in_minutes: 60
      include_targets:
        - id: all_users
          is_registration_required: false
          target_type: group
      is_usable_once: false
      maximum_lifetime_in_minutes: 480
      minimum_lifetime_in_minutes: 60
  #- id: Voice
  #  state: disabled
  #  voice:
  #    include_targets:
  #      - id: all_users
  #        is_registration_required: false
  #        target_type: group
  #    is_office_phone_allowed: false
  #- state: disabled
  #  x509_certificate:
  #    authentication_mode_configuration:
  #      rules: []
  #      x509_certificate_authentication_default_mode: x509CertificateSingleFactor
  #      x509_certificate_default_required_affinity_level: low
  #    certificate_user_bindings:
  #      - priority: 1
  #        trust_affinity_level: low
  #        user_property: onPremisesUserPrincipalName
  #        x509_certificate_field: PrincipalName
  #      - priority: 2
  #        trust_affinity_level: low
  #        user_property: userPrincipalName
  #        x509_certificate_field: RFC822Name
  #    include_targets:
  #      - id: all_users
  #        is_registration_required: false
  #        target_type: group
  #    issuer_hints_configuration:
  #      state: disabled
policy_migration_state: migrationInProgress
registration_enforcement:
authentication_methods_registration_campaign:
  enforce_registration_after_allowed_snoozes: true
  exclude_targets: []
  include_targets:
    - id: all_users
      target_type: group
      targeted_authentication_method: microsoftAuthenticator
  snooze_duration_in_days: 1
  state: disabled
report_suspicious_activity_settings:
  include_target:
    id: all_users
    target_type: group
  state: default
  voice_reporting_code: 0
system_credential_preferences:
  exclude_targets: []
  include_targets:
    - id: all_users
      target_type: group
  state: default
```
